apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alarm-service.fullname" . }}
  labels:
    {{- include "alarm-service.labels" . | nindent 4 }}
data:
  application.yml: |
    server:
      port: {{ .Values.server.port }}
      servlet:
        context-path: /alarm-service
        
    spring:
      application:
        name: alarm-service
      data:
        mongodb:
          uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST_PRIMARY}:${MONGO_PORT_PRIMARY},${MONGO_HOST_SECONDARY_1}:${MONGO_PORT_SECONDARY_1},${MONGO_HOST_SECONDARY_2}:${MONGO_PORT_SECONDARY_2}/alarm-service?replicaSet=rs0&authSource=admin

    kafka:
      cluster:
        uri: ${ELASTIC_HOST}:${ELASTIC_PORT1},${ELASTIC_HOST}:${ELASTIC_PORT2},${ELASTIC_HOST}:${ELASTIC_PORT3}

    springdoc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        enabled: true
        path: /swagger-ui.html

    swagger:
      uri: "/alarm-service"

    logging:
      level:
        root: INFO
        com.multitap.auth: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"