apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "member-service.fullname" . }}
  labels:
    {{- include "member-service.labels" . | nindent 4 }}
data:
  application.yml: |
    server:
      port: {{ .Values.server.port }}

    application:
      name: member-service

    datasource:
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
          use_sql_comments: true
          show_sql: true

    springdoc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /v3/api-docs/swagger-config
        urls:
          - url: /v3/api-docs
            name: API Docs
        disable-swagger-default-url: true
        use-root-path: true

    swagger:
      uri: "/member-service"

    kafka:
      cluster:
        uri: "3.35.228.51:29092,3.35.228.51:39092,3.35.228.51:49092"
      
    logging:
      level:
        root: INFO
        com.multitap.auth: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
