apiVersion: v1
kind: Service
metadata:
  name: kong-gateway-proxy
  namespace: kong
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # 선택적으로 NLB 사용
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  - port: 443
    targetPort: 8443
  selector:
    app: kong