apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-global
  namespace: kong
  labels:
    app: kong-plugins
plugin: jwt
config:
  header_names:
    - Authorization
  run_on_preflight: true
  key_claim_name: sub
  secret_is_base64: false
  maximum_expiration: 86400
  claims_to_verify:
    - exp
---  
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-global
  namespace: kong
  labels:
    app: kong-plugins
plugin: cors
config:
  origins:
    - "*"
    - "http://k8s-kong-konggate-8de0df2ede-4d4e3bf5136f2df6.elb.ap-northeast-2.amazonaws.com"
    - "http://k8s-kong-konggate-8de0df2ede-4d4e3bf5136f2df6.elb.ap-northeast-2.amazonaws.com/swagger-ui/index.html"
    - "http://k8s-kong-konggate-8de0df2ede-4d4e3bf5136f2df6.elb.ap-northeast-2.amazonaws.com/swagger-ui.html"
    - "http://k8s-kong-konggate-8de0df2ede-4d4e3bf5136f2df6.elb.ap-northeast-2.amazonaws.com/v3/api-docs"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  headers:
    - Authorization 
    - Content-Type
    - Accept
    - Accept-Version
    - Content-Length
    - Origin
    - Access-Control-Request-Method
    - Access-Control-Request-Headers
    - X-Requested-With
    - Access-Control-Allow-Origin
  exposed_headers:
    - X-Custom-Header
    - Authorization  
  credentials: true
  max_age: 3600
  preflight_continue: false