apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kong
    meta.helm.sh/release-namespace: kong
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # 이 부분이 중요
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # NLB 타입 명시
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
  creationTimestamp: "2024-11-24T06:11:22Z"
  finalizers:
  - service.k8s.aws/resources
  labels:
    app.kubernetes.io/instance: kong
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway
    app.kubernetes.io/version: "3.6"
    enable-metrics: "true"
    helm.sh/chart: gateway-2.38.0
  name: kong-gateway-proxy
  namespace: kong
  resourceVersion: "6745803"
  uid: 2d65c8e8-3878-480e-ad23-7f29d3e8095e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.171.228
  clusterIPs:
  - 10.100.171.228
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  # Commenting out NLB-specific loadBalancerClass
  # loadBalancerClass: service.k8s.aws/nlb
  ports:
  - name: kong-proxy
    nodePort: 30623
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: kong-proxy-tls
    nodePort: 32566
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: kong
    app.kubernetes.io/name: gateway
  sessionAffinity: None
  type: LoadBalancer