replicaCount: 3

server:
  port: 9100 

image:
  repository: 025066243053.dkr.ecr.ap-northeast-2.amazonaws.com/dg/multi-tap
  tag: auth-1
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "auth-service"

service:
  name: auth-service
  type: LoadBalancer
  port: 80
  targetPort: 9100

ingress:
  enabled: true
  className: kong
  annotations:
    konghq.com/protocols: "http,https"  # HTTP와 HTTPS 프로토콜 허용
  public:
    enabled: true
    annotations:
      konghq.com/methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      konghq.com/plugins: cors-auth-service
      konghq.com/protocols: "http,https"  # HTTP와 HTTPS 프로토콜 허용
      konghq.com/strip_path: "true"
    paths:
      - path: /api/v1/auth/sign-up  # 경로 수정
        pathType: Exact
      - path: /api/v1/auth/sign-in  # 경로 수정
        pathType: Exact
      # Swagger UI 관련 경로 추가
      - path: /swagger-ui.html  # 경로 수정
        pathType: Prefix
      - path: /swagger-ui  # 경로 수정
        pathType: Prefix
      - path: /v3/api-docs  # 경로 수정
        pathType: Prefix
      - path: /webjars  # 경로 수정
        pathType: Prefix
  protected:
    enabled: true
    annotations:
      konghq.com/plugins: jwt-auth-auth-service
      konghq.com/protocols: "http,https"  # HTTP와 HTTPS 프로토콜 허용
    paths:
      - path: /api/v1/auth/
        pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

database:
  host: ""
  port: "3306"
  name: "auth-service"
  username: "" # 시크릿에 추가할 내용들
  password: "" # 시크릿에 추가할 내용들

redis:
  host: ""
  port: ""

jwt:
  secret: ""
  accessTokenValidity: 3600000
  refreshTokenValidity: 604800000

mail:
  host: "smtp.gmail.com"
  port: "587"
  username: ""
  password: "" # 시크릿에 추가 할 내용들

security:
  user:
    name: ""
    password: ""