replicaCount: 3

server:
  port: 9100 

image:
  repository: 025066243053.dkr.ecr.ap-northeast-2.amazonaws.com/dg/multi-tap
  tag: auth-1
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 9100

ingress:
  enabled: true
  className: kong
  annotations:
    konghq.com/strip-path: "true"
  # 인증 인가 필요 없는 회원가입, 로그인
  public:
    enabled: true
    paths:
      - path: /api/v1/auth/sign-up
        pathType: Prefix
      - path: /api/v1/auth/sign-in
        pathType: Prefix
  # 인증 인가 필요한 것들
  protected:
    enabled: true
    paths:
      - path: /api/v3/auth
        pathType: Prefix
    annotations:
      konghq.com/plugins: jwt-auth-{{ .Release.Name }}



resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

database:
  host: ""
  port: "3306"
  name: "auth-service"
  username: "" # 시크릿에 추가할 내용들
  password: "" # 시크릿에 추가할 내용들

redis:
  host: ""
  port: ""

jwt:
  secret: ""
  accessTokenValidity: 3600000
  refreshTokenValidity: 604800000

mail:
  host: "smtp.gmail.com"
  port: "587"
  username: ""
  password: "" # 시크릿에 추가 할 내용들