{{- $sealed := .Files.Get "sealed-secret.yaml" | fromYaml }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: payment-service
  namespace: pay
  labels:
    app.kubernetes.io/instance: payment-service
    app.kubernetes.io/name: payment-service
spec:
  encryptedData:
    {{- $sealed.spec.encryptedData | toYaml | nindent 4 }}
