apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "session-request-service.fullname" . }}
  labels:
    {{- include "session-request-service.labels" . | nindent 4 }}
data:
  application.yml: |
    server:
      port: {{ .Values.server.port }}
      servlet:
        context-path: /session-request-service
        
    spring:
      application:
        name: session-request-service

      datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

      data:
        redis:
          host: ${REDIS_HOST}
          port: ${REDIS_PORT}
          password: ${REDIS_PASSWORD}

      jpa:
        hibernate:
          ddl-auto: update
          show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
            use_sql_comments: true
            show_sql: true

    springdoc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /v3/api-docs/swagger-config
        urls:
          - url: /v3/api-docs
            name: API Docs
        disable-swagger-default-url: true
        use-root-path: true

    

    swagger:
      uri: "/session-request-service"

    kafka:
      cluster:
        uri: ${ELASTIC_HOST}:${ELASTIC_PORT1},${ELASTIC_HOST}:${ELASTIC_PORT2},${ELASTIC_HOST}:${ELASTIC_PORT3}
      
    logging:
      level:
        root: INFO
        com.multitap.auth: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
