apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appLabels.name }}
  labels:
    app: {{ .Values.appLabels.app }}
spec:
  replicas: {{ .Values.replicaCount }}  # Nginx 인스턴스 개수
  selector:
    matchLabels:
      app: {{ .Values.appLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabels.app }}
    spec:
      containers:
        - name: {{ .Values.appLabels.app }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
      #     env:
      #       - name: NGINX_CONFIG
      #         valueFrom:
      #           configMapKeyRef:
      #             name: nginx-config
      #             key: NGINX_CONFIG_VALUE
      #     volumeMounts:
      #       - mountPath: /etc/nginx/conf.d
      #         name: nginx-config-volume
      # volumes:
      #   - name: nginx-config-volume
      #     configMap:
      #       name: nginx-config