apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appLabels.app }}
  ports:
    - port: {{ .Values.service.port }}              # 서비스 내부 포트 (컨테이너가 받는 포트)
      targetPort: {{ .Values.service.targetPort }}       # 컨테이너 내부 포트
      nodePort: {{ .Values.service.nodePort }}        # 외부에서 접근할 노드 포트 (30000~32767)