apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aifeedback-service.fullname" . }}
  labels:
    {{- include "aifeedback-service.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      servelt:
        multipart:
          max-file-size: 20MB
          max-request-size: 20MB
      application:
        name: aifeedback-service

    server:
      port: {{ .Values.server.port }}
      servlet:
        context-path: /aifeedback-service

    gpt:
      api:
        url: ${GPT_API_URL}
        key: ${GPT_API_KEY}
      model: ${GPT_MODEL}
    
    prompt:
      api:
        url: ${PROMPT_API_URL}



    springdoc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /v3/api-docs/swagger-config
        urls:
          - url: /v3/api-docs
            name: API Docs
        disable-swagger-default-url: true
        use-root-path: true

    swagger:
      uri: "/aifeedback-service"

    kafka:
      cluster:
        uri: ${ELASTIC_HOST}:${ELASTIC_PORT1},${ELASTIC_HOST}:${ELASTIC_PORT2},${ELASTIC_HOST}:${ELASTIC_PORT3}

      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

      consumer:
        group-id: feedback-consumer-group # 소비자 그룹 ID
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
    logging:
      level:
        root: INFO
        com.multitap.auth: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
