replicaCount: 1

image:
  repository: 025066243053.dkr.ecr.ap-northeast-2.amazonaws.com/dg/multi-tap
  tag: vidu-5
  pullPolicy: Always

server:
  port: 8080

nameOverride: ""
fullnameOverride: "openvidu-service"

service:
  name: openvidu-service
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
