apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-server.fullname" . }}
  labels:
    {{- include "front-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "front-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "front-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.service.ports }}
          - containerPort: {{ .targetPort }}
            name: {{ .name }}
          {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "front-server.fullname" . }}



