{{- $sealed := .Files.Get "sealed-secret.yaml" | fromYaml }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "front-server.fullname" . }}
  namespace: front
  labels:
    {{- include "front-server.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- $sealed.spec.encryptedData | toYaml | nindent 4 }}
