database:
  host: "43.200.249.170"
  port: "3306"
  name: "mentoring-service"
  username: "adaptors_user"
  password: "12345678"

# database:
#   host: "k8s-mysql-mysql-4fb93d2915-9d929e8800a4e939.elb.ap-northeast-2.amazonaws.com"
#   port: "3306"
#   name: "auth-service" #스키마 이름
#   username: "root"
#   password: "daegwan313@"

sElastic: 
  host: "43.200.249.170"
  port1: "29082"
  port2: "39082"
  port3: "49082"

# database:
#   host: "3.35.228.51"
#   port: "3306"
#   name: "mentoring-service"
#   username: "adaptors_user"
#   password: "12345678"