replicaCount: 1
image:
  repository: 025066243053.dkr.ecr.ap-northeast-2.amazonaws.com/dg/multi-tap
  tag: mentorQ-16
  pullPolicy: Always
server:
  port: 8080
nameOverride: ""
fullnameOverride: "mentoring-query-service"
service:
  name: mentoring-query-service
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
sElastic:
  host: ""
  port1: ""
  port2: ""
  port3: ""
mongo:
  username: ""
  password: ""
  hostPrimary: ""
  portPrimary: ""
  hostSecondary1: ""
  portSecondary1: ""
  hostSecondary2: ""
  portSecondary2: ""
