apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mentoring-service.fullname" . }}
  labels:
    {{- include "mentoring-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mentoring-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mentoring-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "mentoring-service.fullname" . }}
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mentoring-service.fullname" . }}
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "mentoring-service.fullname" . }}
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mentoring-service.fullname" . }}
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mentoring-service.fullname" . }}
                  key: DB_PASSWORD

            - name: ELASTIC_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "mentoring-service.fullname" . }}
                  key: ELASTIC_HOST
            - name: ELASTIC_PORT1
              valueFrom:
                secretKeyRef:
                  name: {{ include "mentoring-service.fullname" . }}
                  key: ELASTIC_PORT1
            - name: ELASTIC_PORT2
              valueFrom:
                secretKeyRef:
                  name: {{ include "mentoring-service.fullname" . }}
                  key: ELASTIC_PORT2
            - name: ELASTIC_PORT3
              valueFrom:
                secretKeyRef:
                  name: {{ include "mentoring-service.fullname" . }}
                  key: ELASTIC_PORT3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "mentoring-service.fullname" . }}
