{{- $sealed := .Files.Get "sealed-secret.yaml" | fromYaml }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mentoring-service
  namespace: mentoring
  labels:
    app.kubernetes.io/instance: mentoring-service
    app.kubernetes.io/name: mentoring-service
spec:
  encryptedData:
    {{- $sealed.spec.encryptedData | toYaml | nindent 4 }}
