replicaCount: 3
appLabels: # deployment 파드
  app: front
  name: front-deployment
service: # svc 파드
  name: front-service
  namespace: front
  type: LoadBalancer
  ports:
    - name: http-client
      port: 3001
      targetPort: 3001
    - name: http-admin
      port: 3002
      targetPort: 3002
    - name: http-web
      port: 3003
      targetPort: 3003
image:
  repository: .dkr.ecr..amazonaws.com/sd# 도커 이미지 이름
  tag: "68"
  pullPolicy: Always
