apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openvidu-service.fullname" . }}
  labels:
    {{- include "openvidu-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openvidu-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openvidu-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config # 도커파일 workdir와 일치
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env: #환경 변수 (configmap)
            - name: OPENVIDU_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "openvidu-service.fullname" . }}
                  key: OPENVIDU_URL
            - name: OPENVIDU_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "openvidu-service.fullname" . }}
                  key: OPENVIDU_SECRET

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "openvidu-service.fullname" . }}
