apiVersion: v1
kind: Secret
metadata:
  name: member-service
  namespace: member
  labels:
    app.kubernetes.io/instance: member-service
    app.kubernetes.io/name: member-service
type: Opaque
stringData:
  DB_HOST: "43.200.249.170"
  DB_USERNAME: "adaptors_user"
  DB_NAME: "member-service"
  DB_PASSWORD: "12345678"
  DB_PORT: "3306"

  ELASTIC_HOST: "43.200.249.170"
  ELASTIC_PORT1: "29082"
  ELASTIC_PORT2: "39082"
  ELASTIC_PORT3: "49082"