apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
data:
  application.yml: |
    server: 
      port: {{ .Values.server.port }} 
    spring:
      application:
        name: auth-service
      datasource:
        url: jdbc:mysql:// ${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD} 
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
          show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
            use_sql_comments: true

      mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true


    jwt:
      secret: ${JWT_SECRET}
      access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
      refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

    security:
      user:
        name: admin
        password: 1234

    springdoc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        enabled: true
        path: /swagger-ui.html

    logging:
      level:
        com:
          multitap:
            auth: DEBUG

            