apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
data:
  application.yml: |
    server: 
      port: {{ .Values.server.port }} 
    spring:
      application:
        name: auth-service
      datasource:
        url: jdbc:mysql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
          show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
            use_sql_comments: true

      mail:
        host: {{ .Values.mail.host }}
        port: {{ .Values.mail.port }}
        properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true

      data:
        redis:
          host: {{ .Values.redis.host }}
          port: {{ .Values.redis.port }}

    jwt:
      access-token-validity: {{ .Values.jwt.accessTokenValidity }}
      refresh-token-validity: {{ .Values.jwt.refreshTokenValidity }}

    security:
      user:
        name: admin
        password: 1234

    springdoc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        enabled: true
        path: /swagger-ui.html

    logging:
      level:
        com:
          multitap:
            auth: DEBUG