apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ .Release.Name }}-jwt-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
config:
  header_names: ["Authorization"]
  maximum_expiration: 86400
  secret_is_base64: false
  claims_to_verify:
    - exp
plugin: jwt