{{- if .Values.ingress.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt-auth-auth-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
plugin: jwt
config:
  header_names:
    - Authorization
  run_on_preflight: false
  key_claim_name: sub
  secret_is_base64: false
  maximum_expiration: 86400
---  
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-auth-service
  namespace: auth
plugin: cors
config:
  origins:
    - "*"
    - "http://afde3cd77af7c47ce92958fdbe874a04-479834.ap-northeast-2.elb.amazonaws.com"
    - "http://afde3cd77af7c47ce92958fdbe874a04-479834.ap-northeast-2.elb.amazonaws.com/swagger-ui/index.html"
    - "http://afde3cd77af7c47ce92958fdbe874a04-479834.ap-northeast-2.elb.amazonaws.com/swagger-ui.html"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  headers:
    - Authorization
    - Content-Type
    - Accept
    - Accept-Version
    - Content-Length
    - Origin
    - Access-Control-Request-Method
    - Access-Control-Request-Headers
    - X-Requested-With
    - Access-Control-Allow-Origin
  exposed_headers:
    - Authorization
    - X-Custom-Header
  credentials: true
  max_age: 3600
  preflight_continue: false
{{- end }}