apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.database.host | toString | b64enc | quote }}
  DB_USERNAME: {{ .Values.database.username | toString | b64enc | quote }}
  DB_NAME: {{ .Values.database.name | toString | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | toString | b64enc | quote }}
  DB_PORT: {{ .Values.database.port | toString | b64enc | quote }}

  JWT_SECRET: {{ .Values.jwt.secret | toString | b64enc | quote }}
  JWT_ACCESS_TOKEN_VALIDITY: {{ .Values.jwt.accessTokenValidity | toString | b64enc | quote }}
  JWT_REFRESH_TOKEN_VALIDITY: {{ .Values.jwt.refreshTokenValidity | toString | b64enc | quote }}
  
  MAIL_USERNAME: {{ .Values.mail.username | toString | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.mail.password | toString | b64enc | quote }}
  MAIL_HOST: {{ .Values.mail.host | toString | b64enc | quote }}
  MAIL_PORT: {{ .Values.mail.port | toString | b64enc | quote }}

  REDIS_HOST: {{ .Values.redis.host | toString | b64enc | quote }}
  REDIS_PORT: {{ .Values.redis.port | toString | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | toString | b64enc | quote }}

  SECURITY_USER_NAME: {{ .Values.security.user.name | toString | b64enc | quote }}
  SECURITY_USER_PASSWORD: {{ .Values.security.user.password | toString | b64enc | quote }}