apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}
type: Opaque
data:
  host: {{ .Values.database.host | b64enc }}
  db-username: {{ .Values.database.username | b64enc }}
  db-password: {{ .Values.database.password | b64enc }}
  jwt-secret: {{ .Values.jwt.secret | b64enc }}
  mail-username: {{ .Values.mail.username | b64enc }}
  mail-password: {{ .Values.mail.password | b64enc }}